// :arch: pure builder for the sanitized local-dev seed SQL served by GET /api/dev/seed.
//        Turns fetched D1 rows into `INSERT OR REPLACE` statements the local loader replays.
// :why: devs need realistic data with no Cloudflare keys; this must NEVER emit PII, so the
//       public-table whitelist is enforced HERE (data-layer), not just by what the caller fetches.
// :rules: only PUBLIC_TABLES are serialized from real data; sensitive tables get SYNTHETIC rows
//         only. Every value goes through sqlLiteral (single-quote escaping) — no interpolation.
// :deps: consumed by src/pages/api/dev/seed.js (passes it {table: rows}). Pure — unit tested.

// Public, non-PII tables. Real rows from these are safe to ship to a contributor's laptop.
export const PUBLIC_TABLES = [
  'content', 'events', 'team', 'categories', 'topics', 'faqs', 'options',
  'press_releases', 'site_pages', 'site_links', 'board_members', 'media',
];

// Sensitive tables (real emails/phones/payments) are NEVER exported. Instead we ship a few
// obviously-fake rows so admin screens that read them still render locally.
export const SYNTHETIC = {
  users: [{
    id: 'dev-local-admin', email: 'dev-local-admin@example.test',
    hashed_password: 'x', name: 'Dev Local Admin', role: 'superadmin', active: 1,
  }],
  event_waitlist: [
    { id: 1, event_id: 'sample', name: 'Sample Waitlister', email: 'waitlist@example.test', phone: '555-0100', party_size: 2 },
  ],
  comments: [
    { id: 'dev-c1', post_id: 'sample', name: 'Sample Commenter', email: 'commenter@example.test', content: 'A sample local comment.', approved: 1 },
  ],
};

// One SQL literal. null/undefined→NULL, boolean→1/0, finite number→bare, object/array→JSON text,
// everything else→a single-quoted string with '' escaping (the only injection-safe path).
export function sqlLiteral(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'boolean') return v ? '1' : '0';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  const s = typeof v === 'object' ? JSON.stringify(v) : String(v);
  return `'${s.replace(/'/g, "''")}'`;
}

// `INSERT OR REPLACE INTO "table" ("c1","c2") VALUES (v1,v2);` — identifiers double-quoted.
export function rowInsert(table, row) {
  const cols = Object.keys(row);
  const names = cols.map((c) => `"${c}"`).join(',');
  const vals = cols.map((c) => sqlLiteral(row[c])).join(',');
  return `INSERT OR REPLACE INTO "${table}" (${names}) VALUES (${vals});`;
}

// All rows for one table, one statement per line. Empty/missing → '' (nothing emitted).
export function tableInserts(table, rows) {
  if (!rows || !rows.length) return '';
  return rows.map((r) => rowInsert(table, r)).join('\n');
}

// Assemble the full seed script from fetched public-table rows + synthetic sensitive rows.
// `fetched` is { tableName: rows[] }; anything not in PUBLIC_TABLES is ignored, so a caller
// accidentally passing a PII table cannot leak it.
export function buildSeedSql(fetched = {}) {
  const parts = ['-- GENERATED by GET /api/dev/seed — sanitized local-dev data. Do not commit.', 'BEGIN TRANSACTION;'];
  for (const table of PUBLIC_TABLES) {
    const sql = tableInserts(table, fetched[table]);
    if (sql) parts.push(`-- ${table}`, sql);
  }
  for (const [table, rows] of Object.entries(SYNTHETIC)) {
    const sql = tableInserts(table, rows);
    if (sql) parts.push(`-- ${table} (synthetic)`, sql);
  }
  parts.push('COMMIT;');
  return parts.join('\n') + '\n';
}
